[project]
# basic information
name = "arteMIS"
description = "arteMIS (Accelerated Ranking and Tuning using multi-metric Interpretability across Scores), is a framework that builds optimal networks networks for downstream analysis."
authors = [
  {name = "Laura Rosina Torres Ortega", email = "rosina.torresortega@wur.nl"},
  {name = "Esteban Charria Giron", email = "esteban.charriagiron@wur.nl"},
]

# This is the version of your project. You can increase the counter to indicate changes
version = "0.1.0"

# it is nice to pin down the version used to develop the project
requires-python = ">=3.13"

readme = "README.md"

dependencies = ["pyyaml", "matchms @ git+https://github.com/matchms/matchms.git@development"]

[project.scripts]
artemis-run = "artemis.cli:main"

[tool.setuptools.packages.find]
include = ["artemis*"]
